security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8099/auth-service/user

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
