server:
  port: 8099



management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

#eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#zuul
zuul:
  ignored-service: 'client-service' # prefix 같은 느낌. htps:port/feign 으로 호출하면 서비스 id가 client-service 인 서비스로 호출
  routes:
    client-service: /feign/**
  sensitive-headers: Cookie,Set-Cookie
