server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/macbook/IdeaProjects/spring-cloud/config-service/src/main/resources/config/example
