server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: file:///Users/hayun/IdeaProjects/spring-cloud-practice/config-service/src/main/resources/config/example
          search-locations: file:///Users/hayun/IdeaProjects/spring-cloud-practice/config-service/src/main/resources/config
